spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${DB_USER}
    password: ${DB_PASS}
    baseline-description: "init"
    baseline-version: 0